esphome:
  name: esp-now-mqtt-bridge
esp32:
  board: esp32dev
  variant: esp32
  framework:
    type: arduino
logger:

external_components:
  - source:
      type: git
      url: https://github.com/u-fire/ESPHomeComponents/

now_mqtt_bridge:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  id: mqtt_broker
  broker: homeassistant.local
  username: mqtt
  password: !secret mqtt_password

